# Generated by Django 5.2.4 on 2025-07-23 20:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='productaction',
            options={'ordering': ['-action_timestamp']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date']},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('brigadeiros', 'Brigadeiros'), ('coxinhas', 'Coxinhas de Morango'), ('tortas', 'Tortas no Pote'), ('kits', 'Kits Festa')], default='brigadeiros', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prices',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productaction',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='size_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='size_selected',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productaction',
            name='action_type',
            field=models.CharField(choices=[('create', 'Criado'), ('update', 'Atualizado'), ('delete', 'Excluído'), ('stock_update', 'Estoque Atualizado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('preparing', 'Preparando'), ('ready', 'Pronto'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
    ]
